let pdir = './index.htm?';

let datax = {
	'default':{
		'0':'首 © 页℠',
		"抖 ® 音℠":"https://creator.douyin.com/",
		"西 ® 瓜℠":"https://studio.ixigua.com/",
		"知 ® 乎℠":"https://www.zhihu.com/creator/manage/creation/all",
		"GreasyFo®k":"https://greasyfork.org/",
		"GitHub":"https://github.com/",
		"文件传输":"https://filehelper.weixin.qq.com/?from=windows&type=recommend",
		"去手写™":"https://pan.baidu.com/aitools/home",
		"宝 ® 典":"http://127.0.0.1/2022/swbd/",
		"在线工具":"https://tool.lu/",
		"©hatGPT":"https://chat.openai.com/",
		"Google":"https://www.google.com/",
		"图片压缩":"https://tinypng.com/",
		"智学网™":"https://www.zhixue.com/login.html",
		"PlayGround":"https://playgroundai.com/create",
		"Fofa":"https://fofa.info/",
		"智慧教育":"https://www.zxx.edu.cn/tchMaterial",
		"W3©school":"https://www.w3school.com.cn/python/index.asp",
		"科技2.0":"http://html.study.bcvet.com.cn/el/proj_21275/index.html",
		"海西培训":"https://fj.rcpxpt.com/singleLoginPage?id=yongchun",
		"ICO图片":"https://convertio.co/zh/png-ico/",
		"IP地址":"https://ipaddress.com/website/github.com",
		"西瓜电影":"https://www.sopoe.cn/xigua/142628.html",
		"文件转换":"https://convertio.co/zh/",
		"DNS列表":"https://devbox.cn/dns",
		"电脑报价":"https://detail.zol.com.cn/cpu/",
		"Win<sup>®</sup>系统":"https://msdn.itellyou.cn/",
		"代理IP":"https://www.kuaidaili.com/free/intr",
		"在线PS":"https://toolwa.com/ps/",
		"分离人声":"https://vocalremover.org/zh/cutter",
		"图片变清":"http://waifu2x.udp.jp/index.zh-CN.html",
		"©Tool<sup>®</sup>": pdir + "tool",
		"™Email℠": pdir + "email",
		"生成HD℠":"https://curlconverter.com/",
		"软件下载":"https://www.zdfans.com/",
		"™S M S℠":"https://sms-activate.org/cn",
		"诊学网™":"http://fjqz.51zhenxue.com/",
		"节 © 点<sup>®</sup>":pdir + "node",
		"Yoncms©gb":"https://yoncms.github.io/",
		"在线编程":"https://anycodes.cn/editor",
		"Java学习":"http://c.biancheng.net/java/70/",
		"教 © 培<sup>®</sup>":pdir + "jiaopei",
		"京 ® 东":"https://www.jd.com/",
		"图片放大":"https://remove.photos/zh-cn/",
		'16位颜色':'file:///H:/manager/color.htm',
		"℠Other™":"file:///H:/manager/other.htm",
		"电 © 影™":"https://www.sanmiw.com/",
		"佐 ® 糖":"https://picwish.cn/",
		"音 ® 乐":"https://www.fangpi.net/",
		"E网通™":"https://www.ewt360.com/",
		"书香博士":"http://www.sxwychina.com/#/",
		"安全教育":"https://quanzhou.xueanquan.com/",
		"学宪法™":"https://static.qspfw.moe.gov.cn/user/#/user/login",
		"MGC工具箱":"http://wap.cpolar.top/tool",
		"谷歌翻译":"https://translate.google.com/?sl=auto&tl=zh-CN&text=Two-factor%20authentication&op=translate",
		"豆包AI":"https://www.doubao.com/chat/",
		"™伊 © 凡<sup>®</sup>":pdir + "yifan"
	},
	'email':{
		'0':'©Email℠',
		'Q Q':'https://mail.qq.com/',
		'QZone':'https://qzone.qq.com/',
		'126':'https://www.126.com/',
		'163':'https://mail.163.com/',
		'Google':'https://gmail.google.com/',
		'无限邮':'https://www.2925.com/'
	},
	'jiaopei':{
		'0':'教 © 培℠',
		'天津政工':'http://tjzgwp.chinahrt.com/',
		'海西培训':'https://fj.rcpxpt.com/',
		'华医网':'https://cme.91huayi.com/',
		'河南专技':'https://hnzj.ghlearning.com/',
		'暑假研修':'https://basic.smartedu.cn/'
	},
	'node':{
		'0':'©Node℠',
		'2dust':'https://github.com/2dust/v2rayN/releases',
		'nodedog':'https://nodedog.org/',
		'FreeClashNode':'https://www.freeclashnode.com/',
		'ClashMeta':'https://clash-meta.github.io/free-nodes/',
		'vergeclash':'https://vergeclash.github.io/free-nodes/',
		'clashverge':'https://clash-verge.github.io/free-nodes/',
		'linuxclash':'https://linuxclash.github.io/',
		'Flikefy':'https://github.com/Flikify/getNode?tab=readme-ov-file',
		'Git节点':'https://github.com/Pawdroid/Free-servers',
		'vpn':'https://github.com/freefq/free',
		'freef':'https://freefq.com/v2ray/',
		'v2cross':'https://v2cross.com/archives/1884',
		'aiboboxx':'https://github.com/aiboboxx/v2rayfree',
		'gaofumei':'https://www.gaofumei.net/networks/12185.html',
		'kejileida':'https://kejileida.net/5781',
		'clashnode':'https://clashnode.xyz/free-v2ray-node/',
		'aliyunjc':'https://www.aliyunjc.net/2796.htm',
		'NiceVPN':'https://github.com/NiceVPN123/NiceVPN',
		'Flik6':'https://github.com/Flik6/getNode?tab=readme-ov-file',
		'Clash':'https://github.com/abshare/abshare.github.io',
		'Clash':'https://ablnk.absslk.xyz/wtB1q4A',
		'Clash':'https://github.com/Pawdroid/Free-servers',
		'proxy':'https://proxy.v2gh.com/https://raw.githubusercontent.com/Pawdroid/Free-servers/main/sub',
		'mirror':'https://mirror.v2gh.com/https://raw.githubusercontent.com/Pawdroid/Free-servers/main/sub',
		'mksshare':'https://github.com/mksshare/mksshare.github.io',
		'freemc':'https://freemc.mcsslk.xyz/oEdGWez',
		'tolinkshare':'https://github.com/tolinkshare/freenode',
		'toshare':'https://toshare.tosslk.xyz/aRAmHXL',
		'Flik6':'https://github.com/Flik6/getNode',
		'zzzgydi':'https://github.com/zzzgydi/clash-verge',
		'v2rayN':'https://github.com/2dust/v2rayN',
		'Clash':'https://github.com/VertexGeek/clash-v2ray?tab=readme-ov-file',
		'2023049':'https://gitlab.com/mianfeifq/share',
		'Free-nodes':'https://clash-meta.github.io/free-nodes/',
		'订阅转换':'https://subconverters.com/',
		'clashtosing':'https://sing-box.xyz/clash-to-sing-box/',
		'Clashtosing':'https://suburl.ljctkp.top/',
		'v2raytosing':'https://subconverters.com/v2ray-to-singbox',
		'Clash':'https://github.com/zzzgydi/clash-verge',
		'Clash':'https://github.com/zzzgydi/clash-verge',
		'Clash':'https://github.com/zzzgydi/clash-verge',
		'v2cross':'https://v2cross.com/1884.html',
		'Nodefree':'https://nodefree.org/',
		'vpn':'https://github.com/mianfeifq/share',
		'v2rayshare':'https://v2rayshare.com/p/2760.html',
		'freenode':'https://freenode.me/'
	},
	'tool':{
		'0':'©TOOL℠',
		"格式HD℠":"https://www.kgtools.cn/compression/header",
		'Curl_Header':'https://tools.gzyunke.cn/curl.html',
		'mp4Tomp3':'https://www.aconvert.com/cn/audio/mp4-to-mp3/',
		'人声分离':'https://vocalremover.org/zh/',
		'Yoncms':'https://yoncms.github.io/',
		'FreeConvert':'https://www.freeconvert.com/zh/convert/video-to-gif',
		'在线Logo':'https://www.shejilogo.com/',
		'Weibo':'https://weibo.com/tiaok',
		'm3u8':'file:///G:/get-m3u8-main/index.html',
		'm3u8':'file:///G:/get-m3u8-main/mitm.html',
		'mp3':'https://www.gequbao.com/music/40037',
		'试卷去手写':'https://pan.baidu.com/aitools/home',
		'那 ® 风':'https://tools.thatwind.com/tool/m3u8downloader',
		'图片视频放大':'https://github.com/k4yt3x/video2x/releases',
		'MkvToImg':'https://www.aconvert.com/cn/image/mkv-to-jpg/',
		'VideoToImg':'https://www.91yasuo.cn/video-to-image',
		'BaseImg':'https://www.lddgo.net/convert/base64-to-image',	
		'图片格式转换':'https://onlineconvertfree.com/zh/converter/images/',
		'python下载':'https://www.python.org/downloads/windows/',
		'图片放大':'https://remove.photos/zh-cn/super-resolution',
		'ICO':'https://toolonline.net/ico-generator',
		'V2℠':'https://v2.info/v2rayn-%E9%85%8D%E7%BD%AE/'
	},
	'yifan':{
		'0':'小 © 宝℠',
		'书香博士':'https://pc.sxwychina.com/jx/index.html#/Home',
		'4399电影':'https://www.4399dmw.com/donghua/',
		'央视少儿':'https://tv.cctv.com/2016/10/28/VIDEO9PCZnv9OJiPxo7hidiy161028.shtml?spm=C55899450127.P94Bw8ryeI2r.0.0'
	}
};
